[target.x86_64-unknown-linux-gnu]
rustflags = ["-C","target-cpu=native"]
#[target.x86_64-unknown-linux-gnu]
## needed for flamegraph https://github.com/flamegraph-rs/flamegraph
#linker = "clang"
#rustflags = ["-Ctarget-cpu=native", "-Clink-arg=-fuse-ld=lld", "-Clink-arg=-Wl,--no-rosegment"]